version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./visualisation_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./visualisation_frontend:/app
      - /app/node_modules
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge